Feature/41
asaka0408/template-ph3-quizy pull request #6
Opened 2022-08-10 09:18 UTC by asaka0408

## 今週の課題
- [ ] 登録済みの問題タイトルが一覧で表示されていますか？
- [ ] 問題タイトルを追加可能ですか？
- [ ] 登録済みの問題タイトルを変更可能ですか？
- [ ] 登録済みの問題タイトルを削除可能ですか？

## 注意点やレビュワーに伝えたいこと(あれば)
ログアウトができなくなってしまっています
画面の構成を考える上で、ファイルを全部用意したかったので、来週のカリキュラムで使うファイルを作成、ルートとコントローラーの作成を行っています。（作っただけで中身は適当）

## 課題が終わっている証跡(スクショ)
<img width="487" alt="スクリーンショット 2022-08-10 18 17 03" src="https://user-images.githubusercontent.com/86900758/183864320-afa14464-ee86-4387-88a3-fe78b0d7a2a5.png">
<img width="237" alt="スクリーンショット 2022-08-10 18 17 31" src="https://user-images.githubusercontent.com/86900758/183864394-59a5c16b-9414-4ea8-b811-f4ca5f2d4bd3.png">
<img width="251" alt="スクリーンショット 2022-08-10 18 17 45" src="https://user-images.githubusercontent.com/86900758/183864440-49238290-bc08-4f0d-b922-75c72685dd49.png">
<img width="301" alt="スクリーンショット 2022-08-10 18 17 57" src="https://user-images.githubusercontent.com/86900758/183864505-2eacfa82-e2e9-41ec-b1c3-2fc7eb69eb6a.png">

2022-08-15 01:26 UTC, daiki-sato requested changes
不要な変更がたくさん入ってますかね？

2022-08-15 01:26 UTC, daiki-sato commented on src/app/Http/Controllers/HomeController.php
> +    public function prefecture_delete(Request $request)
prefecture_delete
これって必要？

2022-08-15 01:26 UTC, daiki-sato commented on src/app/Http/Controllers/HomeController.php
> +    public function prefecture_edit(Request $request)
prefecture_edit
これって必要？

2022-08-15 01:26 UTC, daiki-sato commented on src/resources/views/prefecture_add.blade.php
> +<form action="/home/prefecture/add" method="POST">
例）`<form action="{{ route('bulletin-board.destroy') }}" method="POST">`

と書くことができる
https://qiita.com/yutarou/items/6b3033ccc7c0e7ac6211

2022-08-15 01:26 UTC, daiki-sato commented on src/resources/views/prefecture_add.blade.php
> +<form action="/home/prefecture/add" method="POST">
action="{{ route('') }}

2022-08-15 01:26 UTC, daiki-sato commented on src/resources/views/prefecture_delete.blade.php
> +<form action="/home/prefecture/delete/{{$form->id}}" method="POST">
例）`<form action="{{ route('bulletin-board.destroy') }}" method="POST">`

と書くことができる
https://qiita.com/yutarou/items/6b3033ccc7c0e7ac6211

2022-08-15 01:26 UTC, daiki-sato commented on src/resources/views/prefecture_delete.blade.php
> +  <input type="hidden" name="id" value="{{$form->id}}">
`{{$form->id}}　`
って何の値？

2022-08-15 01:26 UTC, daiki-sato commented on src/resources/views/prefecture_edit.blade.php
> +<form action="/home/prefecture/edit/{{$form->id}}" method="POST">
ditto

2022-08-15 01:26 UTC, daiki-sato commented on src/resources/views/question_edit.blade.php
> +<form action="/home">
ditto

2022-08-15 01:26 UTC, daiki-sato commented on src/resources/views/question_edit.blade.php
> +<form action="/home">
method書いてない

2022-08-15 01:26 UTC, daiki-sato commented on src/resources/views/question_edit.blade.php
> +  <input type="hidden" name="id" value="{{$form->id}}">
インデント

2022-08-15 01:26 UTC, daiki-sato commented on src/resources/views/home.blade.php
> +      <a href="{{ route('prefecture_edit', ['id' => $loop->iteration]) }}">編集</a>
`(['id' => $loop->iteration])` よりも `['id' => $prefecture->id])` の方が良い。

`(['id' => $loop->iteration])`だと、idの値がずれる可能性がある。

### 橋本さんからのコメント↓
```
例えば何かid以外のキーでソートしたらidが順番に並ばなくなるのでだめ
idをdescでソートしてもアウト
ページネーションで100件中、21件目から40件目を取得した時もアウト
whereで条件絞った時も歯抜けになるのでアウトですね
```

2022-08-15 01:26 UTC, daiki-sato commented on src/resources/views/home.blade.php
> +      <a href="{{ route('prefecture_delete', ['id' => $loop->iteration]) }}">削除</a>
ditto

2022-08-16 13:29 UTC, asaka0408 commented on src/resources/views/home.blade.php
> +      <a href="{{ route('prefecture_edit', ['id' => $loop->iteration]) }}">編集</a>
表示順番がレコード順と違ったらずれてしまうってことですね、理解です

2022-08-16 13:30 UTC, asaka0408 commented on src/app/Http/Controllers/HomeController.php
> +    public function prefecture_delete(Request $request)
不要なことってあるんですか？！
最初の表示についての処理なんですけど、なくす場合ってどうなるんでしょうか。。。？
（以下同）

2022-08-16 13:30 UTC, asaka0408 commented on src/resources/views/prefecture_add.blade.php
> +<form action="/home/prefecture/add" method="POST">
これaタグ以外でもできるんだ！やります！

2022-08-16 13:31 UTC, asaka0408 commented on src/resources/views/prefecture_delete.blade.php
> +  <input type="hidden" name="id" value="{{$form->id}}">
prefectureテーブルのidなんですけど、教科書と同じ変数でやったまま編集できていなかったので名前に直します！

2022-08-16 13:31 UTC, asaka0408 commented on src/resources/views/question_edit.blade.php
> +<form action="/home">
あ

2022-08-16 13:31 UTC, asaka0408 commented on src/resources/views/question_edit.blade.php
> +  <input type="hidden" name="id" value="{{$form->id}}">
なおします

2022-08-20 07:13 UTC, daiki-sato commented on src/app/Http/Controllers/HomeController.php
> +    public function prefecture_delete(Request $request)
理解です。
修正しなくてOKです^^

2022-08-20 07:13 UTC, daiki-sato commented on src/app/Http/Controllers/HomeController.php
> +    public function prefecture_edit(Request $request)
理解です。
修正しなくてOKです^^

2022-08-20 07:13 UTC, daiki-sato commented on src/resources/views/prefecture_add.blade.php
> +<form action="/home/prefecture/add" method="POST">
yea

2022-08-20 07:14 UTC, daiki-sato commented on src/resources/views/home.blade.php
> +      <a href="{{ route('prefecture_edit', ['id' => $loop->iteration]) }}">編集</a>
ya

2022-08-25 05:09 UTC, asaka0408 commented on src/resources/views/prefecture_add.blade.php
> +<form action="/home/prefecture/add" method="POST">
done

2022-08-25 05:10 UTC, asaka0408 commented on src/resources/views/prefecture_delete.blade.php
> +<form action="/home/prefecture/delete/{{$form->id}}" method="POST">
done

2022-08-25 05:29 UTC, asaka0408 commented on src/resources/views/prefecture_delete.blade.php
> +<form action="/home/prefecture/delete/{{$form->id}}" method="POST">
ここを変えるとパラメーターがうまく行かなくてエラーになっちゃうから保留

2022-08-25 05:32 UTC, asaka0408 commented on src/resources/views/prefecture_delete.blade.php
> +  <input type="hidden" name="id" value="{{$form->id}}">
なおした！！！！

2022-08-25 05:37 UTC, asaka0408 commented on src/resources/views/prefecture_edit.blade.php
> +<form action="/home/prefecture/edit/{{$form->id}}" method="POST">
これもパラメーターがうまく使いこなせてない、、、、、、、、、、

2022-08-25 05:37 UTC, asaka0408 commented on src/resources/views/question_edit.blade.php
> +<form action="/home">
done

2022-08-25 05:39 UTC, asaka0408 commented on src/resources/views/home.blade.php
> +      <a href="{{ route('prefecture_edit', ['id' => $loop->iteration]) }}">編集</a>
done

2022-09-13 08:49 UTC, merged